name: ${name}
version: ${version}
main: ${main}
folia-supported: true
api-version: ${apiVersion}
authors: [CrazyDev22]

softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

commands:
  holoui:
    aliases: [holo, hui, holou, hu]

permissions:
  holoui.preview:
    description: "Allow opening a preview menu for a specific block with holoui.preview.<type>"
    default: op
  holoui.open:
    description: "Open a specific menu with holoui.open.<name>"
    default: op
  holoui.command.list:
    description: "List all menus"
    default: op
  holoui.command.open:
    description: "Open a menu"
    default: op
  holoui.command.close:
    description: "Close the current menu"
    default: op
  holoui.command.back:
    description: "Return to the last opened menu"
    default: op
  holoui.command.server:
    description: "Builder server status"
    default: op
  holoui.command.server.start:
    description: "Start the builder server"
    default: op
  holoui.command.server.stop:
    description: "Stops the builder server"
    default: op
