name: ${name}
version: ${version}
main: ${main}
api-version: ${apiVersion}
authors: [CrazyDev22]

softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot